/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as GetInvolvedRouteImport } from './routes/get-involved'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as OurWorkRouteImport } from './routes/our-work'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as TeamRouteImport } from './routes/team'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const GetInvolvedRoute = GetInvolvedRouteImport.update({
  id: '/get-involved',
  path: '/get-involved',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const OurWorkRoute = OurWorkRouteImport.update({
  id: '/our-work',
  path: '/our-work',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/gallery': typeof GalleryRoute
  '/get-involved': typeof GetInvolvedRoute
  '/impact': typeof ImpactRoute
  '/our-work': typeof OurWorkRoute
  '/partners': typeof PartnersRoute
  '/team': typeof TeamRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/gallery': typeof GalleryRoute
  '/get-involved': typeof GetInvolvedRoute
  '/impact': typeof ImpactRoute
  '/our-work': typeof OurWorkRoute
  '/partners': typeof PartnersRoute
  '/team': typeof TeamRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/gallery': typeof GalleryRoute
  '/get-involved': typeof GetInvolvedRoute
  '/impact': typeof ImpactRoute
  '/our-work': typeof OurWorkRoute
  '/partners': typeof PartnersRoute
  '/team': typeof TeamRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/gallery'
    | '/get-involved'
    | '/impact'
    | '/our-work'
    | '/partners'
    | '/team'
    | '/projects/$slug'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/gallery'
    | '/get-involved'
    | '/impact'
    | '/our-work'
    | '/partners'
    | '/team'
    | '/projects/$slug'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/gallery'
    | '/get-involved'
    | '/impact'
    | '/our-work'
    | '/partners'
    | '/team'
    | '/projects/$slug'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  GalleryRoute: typeof GalleryRoute
  GetInvolvedRoute: typeof GetInvolvedRoute
  ImpactRoute: typeof ImpactRoute
  OurWorkRoute: typeof OurWorkRoute
  PartnersRoute: typeof PartnersRoute
  TeamRoute: typeof TeamRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-involved': {
      id: '/get-involved'
      path: '/get-involved'
      fullPath: '/get-involved'
      preLoaderRoute: typeof GetInvolvedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-work': {
      id: '/our-work'
      path: '/our-work'
      fullPath: '/our-work'
      preLoaderRoute: typeof OurWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  GalleryRoute: GalleryRoute,
  GetInvolvedRoute: GetInvolvedRoute,
  ImpactRoute: ImpactRoute,
  OurWorkRoute: OurWorkRoute,
  PartnersRoute: PartnersRoute,
  TeamRoute: TeamRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
